version: '3'
services:
  model_service:
    build: .
    restart: "always"
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000