version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.4
    container_name: etcd
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --data-dir=/etcd-data
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379

  patroni1:
    image: patroni:latest
    container_name: patroni1
    environment:
      PATRONI_NAME: patroni1
      PATRONI_ETCD_HOST: etcd
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni1:8008
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni1:5432
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      # Par exemple, si vous voulez imposer un mot de passe "0000" à l'utilisateur postgres :
      PATRONI_POSTGRESQL_PASSWORD: "0000"
    ports:
      - "5433:5432"   # On mappe le port local 5433 vers le 5432 du conteneur
      - "8008:8008"
    depends_on:
      - etcd

  patroni2:
    image: patroni:latest
    container_name: patroni2
    environment:
      PATRONI_NAME: patroni2
      PATRONI_ETCD_HOST: etcd
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni2:8008
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni2:5432
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_POSTGRESQL_PASSWORD: "0000"   # idem
    ports:
      - "5434:5432"   # On mappe le port local 5434 vers le 5432 du conteneur
      - "8009:8008"   # on change pour ne pas se télescoper avec patroni1
    depends_on:
      - etcd
